version: '3.5'
services:
  web:
    build: .
    environment:
      MYENV: FENV
    volumes:
      - .:/code
        
  web_run:
    extends:
      service: web 
    command: flask run 
    ports:
      - "8000:8000"
  database:
    container_name: postgres
    image: postgres:latest
    volumes:
      - db_volume:/var/lib/postgresql

volumes:
  db_volume: